import { StyleSheet } from 'react-native';
import { Colors, Fonts } from '@/constants/theme';

/**
 * Shared StyleSheet for the Train tab's Schedule feature — the screen header,
 * schedule list/calendar, workout detail view and the create-workout sheet all
 * reference these keys. Extracted verbatim (pre-existing StyleSheet tech debt).
 */
export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.base },

  header: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 10,
    marginBottom: 4,
  },
  appTitle: {
    fontFamily: Fonts.display,
    fontSize: 26,
    color: Colors.primary,
    letterSpacing: 4,
    lineHeight: 28,
  },
  pageLabel: {
    fontFamily: Fonts.display,
    fontSize: 11,
    color: '#606060',
    letterSpacing: 2,
    marginTop: 2,
  },
  backBtn: { padding: 4 },

  content: { paddingHorizontal: 16, paddingTop: 14, paddingBottom: 100 },

  tabSwitcher: {
    paddingHorizontal: 16,
    paddingBottom: 10,
  },

  loadingRow: {
    paddingVertical: 20,
    alignItems: 'center',
  },

  // Calendar
  calendarCard: {
    flexDirection: 'row',
    gap: 6,
    backgroundColor: Colors.surface,
    borderRadius: 20,
    padding: 16,
    marginBottom: 14,
  },
  dayCol: { flex: 1, alignItems: 'center' },
  dayDot: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: 10,
    backgroundColor: Colors.base,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  dayDotActive: { backgroundColor: Colors.accent },
  emptyDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: '#333' },
  dayLabel: { fontFamily: Fonts.display, fontSize: 9, letterSpacing: 1, color: Colors.muted },
  dayLabelActive: { color: Colors.accent },

  // Section row
  sectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  sectionLabel: { fontFamily: Fonts.display, fontSize: 12, letterSpacing: 3, color: Colors.muted },
  newBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 7,
    paddingHorizontal: 14,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: Colors.accent,
    backgroundColor: Colors.accentRing,
  },
  newBtnText: { fontFamily: Fonts.display, fontSize: 11, letterSpacing: 1.5, color: Colors.accent },

  // Workout card
  workoutCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: Colors.surface,
    borderRadius: 18,
    padding: 14,
    paddingHorizontal: 16,
    marginBottom: 10,
    borderWidth: 1.5,
    borderColor: Colors.borderDefault,
  },
  workoutIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: Colors.base,
    alignItems: 'center',
    justifyContent: 'center',
  },
  workoutInfo: { flex: 1 },
  workoutName: { fontFamily: Fonts.display, fontSize: 17, letterSpacing: 2, color: Colors.primary },
  workoutMeta: { fontFamily: Fonts.body, fontSize: 12, color: Colors.muted },
  deleteBtn: { padding: 6, borderRadius: 8 },

  // Empty state
  emptyState: {
    alignItems: 'center',
    padding: 40,
    backgroundColor: Colors.surface,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: Colors.borderDefault,
    borderStyle: 'dashed',
  },
  emptyTitle: {
    fontFamily: Fonts.display,
    fontSize: 16,
    letterSpacing: 3,
    color: Colors.primary,
    marginBottom: 6,
  },
  emptySubtitle: { fontFamily: Fonts.body, fontSize: 13, color: Colors.muted, textAlign: 'center' },

  // Detail view
  detailCard: { backgroundColor: '#000', borderRadius: 20, padding: 20, marginBottom: 14 },
  detailCardTop: { flexDirection: 'row', alignItems: 'center', gap: 14, marginBottom: 12 },
  detailIconWrap: {
    width: 50,
    height: 50,
    borderRadius: 14,
    backgroundColor: 'rgba(230,48,48,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(230,48,48,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailName: { fontFamily: Fonts.display, fontSize: 26, letterSpacing: 3, color: Colors.primary },
  detailMeta: { fontFamily: Fonts.body, fontSize: 12, color: Colors.secondary, letterSpacing: 2 },
  progressRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  progressLabel: { fontFamily: Fonts.display, fontSize: 11, letterSpacing: 1, color: Colors.muted },
  progressTrack: {
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 4,
    overflow: 'hidden',
    flexDirection: 'row',
  },
  progressFill: { backgroundColor: Colors.accent, borderRadius: 4 },

  // Exercise card
  exCard: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    padding: 14,
    paddingHorizontal: 16,
    marginBottom: 10,
  },
  exCardTop: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  exIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: Colors.base,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    alignItems: 'center',
    justifyContent: 'center',
  },
  exIconActive: {
    backgroundColor: 'rgba(230,48,48,0.1)',
    borderColor: 'rgba(230,48,48,0.3)',
  },
  exInfo: { flex: 1 },
  exName: { fontFamily: Fonts.bodySemiBold, fontSize: 15, color: Colors.primary, marginBottom: 2 },
  exMeta: { fontFamily: Fonts.body, fontSize: 12, color: Colors.muted },
  exBadge: {
    backgroundColor: Colors.base,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  exBadgeText: { fontFamily: Fonts.display, fontSize: 17, color: Colors.primary },
  setsRow: { flexDirection: 'row', gap: 8 },
  setBtn: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 6,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: Colors.borderDefault,
    backgroundColor: Colors.base,
    alignItems: 'center',
    justifyContent: 'center',
  },
  setBtnDone: { borderColor: Colors.accent, backgroundColor: 'rgba(230,48,48,0.12)' },
  setBtnLabel: { fontFamily: Fonts.display, fontSize: 11, letterSpacing: 1, color: Colors.muted },

  // CTAs
  startBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: Colors.accent,
    borderRadius: 16,
    height: 52,
    marginTop: 6,
  },
  startBtnText: { fontFamily: Fonts.display, fontSize: 15, letterSpacing: 3, color: Colors.primary },
  doneCard: {
    backgroundColor: '#0a1f0a',
    borderWidth: 1,
    borderColor: '#1a3a1a',
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    marginTop: 6,
  },
  doneTitle: {
    fontFamily: Fonts.display,
    fontSize: 22,
    letterSpacing: 3,
    color: Colors.primary,
    marginBottom: 4,
  },
  doneSub: { fontFamily: Fonts.body, fontSize: 13, color: Colors.muted, marginBottom: 18 },
  doneBtn: {
    backgroundColor: Colors.accent,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 28,
  },
  doneBtnText: { fontFamily: Fonts.display, fontSize: 14, letterSpacing: 2, color: Colors.primary },
  cancelBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1.5,
    borderColor: Colors.borderDefault,
    borderRadius: 16,
    height: 52,
    marginTop: 6,
  },
  cancelBtnText: { fontFamily: Fonts.display, fontSize: 13, letterSpacing: 2, color: Colors.muted },

  // Modal
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.82)',
    zIndex: 100,
  },
  sheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: Colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '88%',
    zIndex: 101,
  },
  sheetContent: { padding: 24 },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  sheetTitle: { fontFamily: Fonts.display, fontSize: 22, letterSpacing: 3, color: Colors.primary },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.elevated,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fieldLabel: {
    fontFamily: Fonts.display,
    fontSize: 10,
    letterSpacing: 2,
    color: Colors.muted,
    marginBottom: 5,
  },
  input: {
    backgroundColor: Colors.base,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.borderDefault,
    paddingHorizontal: 14,
    paddingVertical: 11,
    color: Colors.primary,
    fontFamily: Fonts.body,
    fontSize: 14,
  },
  inputOnSurface: { backgroundColor: Colors.surface },
  inputSmall: {
    fontFamily: Fonts.display,
    fontSize: 16,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  dayPicker: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 4 },
  dayPill: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: Colors.borderDefault,
  },
  dayPillActive: { borderColor: Colors.accent, backgroundColor: Colors.accentRing },
  dayPillText: { fontFamily: Fonts.display, fontSize: 11, letterSpacing: 1, color: Colors.muted },
  dayPillTextActive: { color: Colors.accent },
  exerciseBuilder: {
    backgroundColor: Colors.base,
    borderRadius: 14,
    padding: 14,
    marginBottom: 14,
  },
  exFieldsRow: { flexDirection: 'row', gap: 8, marginBottom: 10 },
  miniLabel: {
    fontFamily: Fonts.display,
    fontSize: 9,
    letterSpacing: 1,
    color: Colors.muted,
    marginBottom: 4,
  },
  addExBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: Colors.accent,
    borderRadius: 10,
    paddingVertical: 10,
  },
  addExBtnDisabled: { backgroundColor: Colors.elevated },
  addExBtnText: { fontFamily: Fonts.display, fontSize: 12, letterSpacing: 2, color: Colors.primary },
  addedExRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: Colors.base,
    borderRadius: 12,
    padding: 10,
    paddingHorizontal: 14,
    marginBottom: 8,
  },
  addedExIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: Colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addedExName: { fontFamily: Fonts.bodySemiBold, fontSize: 13, color: Colors.primary },
  addedExMeta: { fontFamily: Fonts.body, fontSize: 11, color: Colors.muted },
  saveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: Colors.accent,
    borderRadius: 14,
    height: 54,
  },
  saveBtnDisabled: { backgroundColor: Colors.elevated },
  saveBtnText: { fontFamily: Fonts.display, fontSize: 15, letterSpacing: 3, color: Colors.primary },
});
