import { StyleSheet } from 'react-native';
import { Colors, Fonts } from '@/constants/theme';

/**
 * Shared StyleSheets for the Compete tab, extracted verbatim from the original
 * screen. These blocks are cross-referenced by several sibling components
 * (e.g. `styles` by the screen header and RivalsContent, `cStyles` by the
 * challenge cards and ChallengesContent, `gStyles` by GlobalContent and
 * ChallengesContent), so they live in one module rather than being duplicated.
 *
 * This is pre-existing StyleSheet tech debt kept as-is per AGENTS.md — the goal
 * of this extraction is composition, not a NativeWind migration.
 */

// ─── Main / screen + rivals styles ───────────────────────────────────────────
export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: Colors.base,
  },
  header: {
    paddingTop: 20,
    paddingHorizontal: 16,
    paddingBottom: 0,
  },
  logo: {
    fontFamily: Fonts.display,
    fontSize: 30,
    letterSpacing: 5,
    color: '#fff',
    lineHeight: 32,
  },
  subtitle: {
    fontFamily: Fonts.display,
    fontSize: 11,
    color: '#555',
    letterSpacing: 4,
    marginTop: 4,
  },
  segmented: {
    flexDirection: 'row',
    backgroundColor: '#1e1e1e',
    borderRadius: 14,
    padding: 4,
    marginTop: 16,
    gap: 3,
    borderWidth: 1,
    borderColor: '#2a2a2a',
  },
  segTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 9,
    paddingHorizontal: 4,
    borderRadius: 10,
  },
  segTabActive: {
    backgroundColor: '#fff',
  },
  segLabel: {
    fontFamily: Fonts.display,
    fontSize: 11,
    letterSpacing: 1.5,
    color: '#555',
  },
  segLabelActive: {
    color: '#000',
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 96,
  },
  chipsRow: {
    flexDirection: 'row',
    gap: 6,
    paddingTop: 16,
    paddingBottom: 4,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#2a2a2a',
    backgroundColor: 'transparent',
  },
  chipActive: {
    borderColor: '#fff',
    backgroundColor: '#fff',
  },
  chipLabel: {
    fontFamily: Fonts.display,
    fontSize: 11,
    letterSpacing: 1,
    color: '#555',
  },
  chipLabelActive: {
    color: '#000',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 10,
  },
  rowMe: {
    backgroundColor: '#fff',
    transform: [{ scale: 1.025 }],
  },
  rowOther: {
    backgroundColor: '#1e1e1e',
    borderWidth: 1,
    borderColor: '#2a2a2a',
  },
  rankBox: {
    width: 28,
    alignItems: 'center',
    flexShrink: 0,
  },
  rankNum: {
    fontFamily: Fonts.display,
    fontSize: 13,
    color: '#505050',
  },
  rowCenter: {
    flex: 1,
    minWidth: 0,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  userName: {
    fontFamily: Fonts.display,
    fontSize: 15,
    letterSpacing: 1,
    color: '#fff',
  },
  userNameMe: {
    color: '#000',
  },
  youTag: {
    fontFamily: Fonts.display,
    fontSize: 9,
    color: Colors.accent,
    marginLeft: 8,
    letterSpacing: 1,
  },
  barTrack: {
    height: 4,
    backgroundColor: '#2a2a2a',
    borderRadius: 4,
    overflow: 'hidden',
  },
  barTrackMe: {
    backgroundColor: 'rgba(0,0,0,0.1)',
  },
  barFillMe: {
    height: 4,
    borderRadius: 4,
    backgroundColor: '#000',
  },
  barFillOther: {
    height: 4,
    borderRadius: 4,
  },
  prBox: {
    alignItems: 'flex-end',
    flexShrink: 0,
  },
  prValue: {
    fontFamily: Fonts.display,
    fontSize: 28,
    lineHeight: 28,
  },
  prUnit: {
    fontFamily: Fonts.display,
    fontSize: 9,
    color: '#505050',
    letterSpacing: 1,
  },
  prUnitMe: {
    color: '#888',
  },
  footerNote: {
    textAlign: 'center',
    paddingVertical: 16,
    paddingBottom: 8,
    fontFamily: Fonts.display,
    fontSize: 10,
    color: '#383838',
    letterSpacing: 2,
  },
});

// ─── Rivals-only styles ──────────────────────────────────────────────────────
export const rivalsStyles = StyleSheet.create({
  loadingBox: {
    alignItems: 'center',
    paddingVertical: 48,
  },
  emptyBox: {
    alignItems: 'center',
    backgroundColor: '#1e1e1e',
    borderRadius: 18,
    paddingVertical: 48,
    paddingHorizontal: 20,
    gap: 8,
  },
  emptyTitle: {
    fontFamily: Fonts.display,
    fontSize: 18,
    letterSpacing: 2,
    color: '#fff',
  },
  emptySub: {
    fontFamily: Fonts.body,
    fontSize: 13,
    color: '#555',
    textAlign: 'center',
  },
});

// ─── Challenge card / list styles ────────────────────────────────────────────
export const cStyles = StyleSheet.create({
  card: {
    backgroundColor: '#1e1e1e',
    borderRadius: 18,
    padding: 16,
    paddingHorizontal: 18,
    marginBottom: 12,
    borderWidth: 1,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
    marginBottom: 14,
  },
  iconBox: {
    width: 46,
    height: 46,
    borderRadius: 13,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  cardTitle: {
    fontFamily: Fonts.display,
    fontSize: 18,
    letterSpacing: 2,
    color: '#fff',
    marginBottom: 3,
  },
  cardDesc: {
    fontFamily: Fonts.body,
    fontSize: 12,
    color: '#707070',
    lineHeight: 18,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 14,
    marginBottom: 14,
    flexWrap: 'wrap',
  },
  statItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  statText: {
    fontFamily: Fonts.body,
    fontSize: 11,
    color: '#606060',
  },
  miniRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 7,
  },
  miniMedal: {
    width: 20,
    alignItems: 'center',
  },
  miniName: {
    flex: 1,
    fontFamily: Fonts.body,
    fontSize: 13,
    color: '#b0b0b0',
  },
  miniVal: {
    fontFamily: Fonts.display,
    fontSize: 15,
    color: '#fff',
  },
  miniUnit: {
    fontFamily: Fonts.body,
    fontSize: 10,
    color: '#555',
  },
  btnRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 14,
  },
  btnJoin: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 12,
  },
  btnJoinText: {
    fontFamily: Fonts.display,
    fontSize: 12,
    letterSpacing: 2,
    color: '#fff',
  },
  btnJoinedInactive: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: '#2a2a2a',
  },
  btnJoinedText: {
    fontFamily: Fonts.display,
    fontSize: 12,
    letterSpacing: 2,
    color: '#555',
  },
  btnViewAll: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1.5,
    backgroundColor: 'transparent',
  },
  btnViewAllText: {
    fontFamily: Fonts.display,
    fontSize: 12,
    letterSpacing: 2,
  },
  sectionLabel: {
    fontFamily: Fonts.display,
    fontSize: 11,
    letterSpacing: 3,
    color: '#555',
    marginBottom: 10,
  },
  friendHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 4,
  },
  friendTitle: {
    fontFamily: Fonts.display,
    fontSize: 14,
    letterSpacing: 2,
    color: '#fff',
  },
  friendSubtitle: {
    fontFamily: Fonts.body,
    fontSize: 12,
    color: '#555',
    marginBottom: 14,
  },
  moreCount: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#252525',
    borderWidth: 1,
    borderColor: '#2a2a2a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  moreCountText: {
    fontFamily: Fonts.display,
    fontSize: 11,
    color: '#555',
  },
  challengeFriendBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 13,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(230,48,48,0.25)',
  },
  challengeFriendBtnText: {
    fontFamily: Fonts.display,
    fontSize: 12,
    letterSpacing: 2,
    color: Colors.accent,
  },
});

// ─── Create Challenge Modal styles ───────────────────────────────────────────
export const mStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.75)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: '#1e1e1e',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
    maxHeight: '92%',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  title: {
    fontFamily: Fonts.display,
    fontSize: 20,
    letterSpacing: 3,
    color: '#fff',
    flex: 1,
  },
  closeBtn: {
    padding: 4,
  },
  selectedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#252525',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#2a2a2a',
    marginBottom: 4,
  },
  selectedName: {
    flex: 1,
    fontFamily: Fonts.bodyMedium,
    fontSize: 14,
    color: '#fff',
  },
  changeBtn: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#383838',
  },
  changeBtnText: {
    fontFamily: Fonts.display,
    fontSize: 9,
    letterSpacing: 1,
    color: '#888',
  },
  searchWrap: {
    marginBottom: 10,
    justifyContent: 'center' as const,
  },
  searchIcon: {
    position: 'absolute' as const,
    left: 12,
    zIndex: 1,
  },
  searchInput: {
    backgroundColor: '#252525',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#333',
    paddingVertical: 10,
    paddingLeft: 36,
    paddingRight: 14,
    fontFamily: Fonts.body,
    fontSize: 13,
    color: '#fff',
  },
  friendList: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2a2a2a',
    overflow: 'hidden' as const,
    marginBottom: 4,
  },
  friendItem: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 12,
    backgroundColor: '#252525',
  },
  friendItemBorder: {
    borderTopWidth: 1,
    borderTopColor: '#2a2a2a',
  },
  friendItemName: {
    fontFamily: Fonts.bodyMedium,
    fontSize: 13,
    color: '#fff',
  },
  friendItemUsername: {
    fontFamily: Fonts.body,
    fontSize: 11,
    color: '#555',
  },
  noFriendsText: {
    fontFamily: Fonts.body,
    fontSize: 13,
    color: '#555',
    textAlign: 'center' as const,
    paddingVertical: 16,
  },
  errorRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
    backgroundColor: 'rgba(230,48,48,0.08)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(230,48,48,0.2)',
    padding: 12,
    marginBottom: 12,
  },
  errorText: {
    flex: 1,
    fontFamily: Fonts.body,
    fontSize: 12,
    color: Colors.accent,
    lineHeight: 18,
  },
  label: {
    fontFamily: Fonts.display,
    fontSize: 10,
    letterSpacing: 3,
    color: '#555',
    marginBottom: 10,
  },
  chip: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#2a2a2a',
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipActive: {
    borderColor: Colors.accent,
    backgroundColor: 'rgba(230,48,48,0.1)',
  },
  chipLabel: {
    fontFamily: Fonts.display,
    fontSize: 10,
    letterSpacing: 1,
    color: '#555',
  },
  chipLabelActive: {
    color: Colors.accent,
  },
  sendBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 14,
  },
  sendBtnText: {
    fontFamily: Fonts.display,
    fontSize: 14,
    letterSpacing: 3,
    color: '#fff',
  },
});

// ─── Global leaderboard styles ───────────────────────────────────────────────
export const gStyles = StyleSheet.create({
  searchWrap: {
    position: 'relative',
    marginTop: 16,
    marginBottom: 4,
    justifyContent: 'center',
  },
  searchIcon: {
    position: 'absolute',
    left: 14,
    zIndex: 1,
  },
  searchInput: {
    backgroundColor: '#1e1e1e',
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#2a2a2a',
    paddingVertical: 12,
    paddingLeft: 42,
    paddingRight: 14,
    fontFamily: Fonts.body,
    fontSize: 14,
    color: '#fff',
  },
  card: {
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 10,
    marginTop: 6,
  },
  cardMe: {
    backgroundColor: '#fff',
    transform: [{ scale: 1.025 }],
  },
  cardOther: {
    backgroundColor: '#1e1e1e',
    borderWidth: 1,
    borderColor: '#2a2a2a',
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 10,
  },
  rankBox: {
    width: 28,
    alignItems: 'center',
    flexShrink: 0,
  },
  rankNum: {
    fontFamily: Fonts.display,
    fontSize: 13,
    color: '#505050',
  },
  infoCol: {
    flex: 1,
    minWidth: 0,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 2,
  },
  name: {
    fontFamily: Fonts.display,
    fontSize: 15,
    letterSpacing: 1,
    color: '#fff',
  },
  nameMe: {
    color: '#000',
  },
  youTag: {
    fontFamily: Fonts.display,
    fontSize: 9,
    color: Colors.accent,
    letterSpacing: 1,
  },
  sub: {
    fontFamily: Fonts.body,
    fontSize: 11,
    color: '#555',
  },
  subMe: {
    color: '#888',
  },
  totalBox: {
    alignItems: 'flex-end',
    flexShrink: 0,
  },
  totalVal: {
    fontFamily: Fonts.display,
    fontSize: 26,
    lineHeight: 26,
  },
  totalLabel: {
    fontFamily: Fonts.display,
    fontSize: 9,
    color: '#505050',
    letterSpacing: 1,
  },
  totalLabelMe: {
    color: '#888',
  },
  statsRow: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 10,
  },
  statBox: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    borderRadius: 10,
    paddingVertical: 7,
    paddingHorizontal: 5,
    alignItems: 'center',
    gap: 2,
  },
  statBoxMe: {
    backgroundColor: 'rgba(0,0,0,0.07)',
  },
  statVal: {
    fontFamily: Fonts.display,
    fontSize: 16,
    color: '#fff',
  },
  statValMe: {
    color: '#000',
  },
  statLabel: {
    fontFamily: Fonts.display,
    fontSize: 8,
    color: '#555',
    letterSpacing: 1,
  },
  statLabelMe: {
    color: '#888',
  },
  barTrack: {
    height: 4,
    backgroundColor: '#2a2a2a',
    borderRadius: 4,
    overflow: 'hidden',
  },
  barTrackMe: {
    backgroundColor: 'rgba(0,0,0,0.1)',
  },
  barFillMe: {
    height: 4,
    borderRadius: 4,
    backgroundColor: '#000',
  },
  barFillOther: {
    height: 4,
    borderRadius: 4,
  },
  emptyCard: {
    alignItems: 'center',
    backgroundColor: '#1e1e1e',
    borderRadius: 18,
    paddingVertical: 48,
    paddingHorizontal: 20,
    gap: 8,
    marginTop: 6,
  },
  emptyTitle: {
    fontFamily: Fonts.display,
    fontSize: 18,
    letterSpacing: 2,
    color: '#fff',
  },
  emptySub: {
    fontFamily: Fonts.body,
    fontSize: 13,
    color: '#555',
  },
  footerNote: {
    textAlign: 'center',
    paddingTop: 16,
    paddingBottom: 8,
    fontFamily: Fonts.display,
    fontSize: 10,
    color: '#383838',
    letterSpacing: 2,
  },
  searchSpinner: {
    position: 'absolute',
    right: 14,
  },
  flagText: {
    fontSize: 14,
  },
  skeletonCard: {
    opacity: 0.45,
  },
  skeletonBlock: {
    backgroundColor: '#2a2a2a',
    borderRadius: 6,
  },
  pinnedWrap: {
    marginBottom: 4,
  },
  pinnedLabel: {
    fontFamily: Fonts.display,
    fontSize: 10,
    letterSpacing: 3,
    color: Colors.accent,
    marginBottom: 4,
    marginTop: 16,
  },
  unrankedCard: {
    alignItems: 'center',
    backgroundColor: '#1e1e1e',
    borderRadius: 18,
    paddingVertical: 32,
    paddingHorizontal: 20,
    gap: 8,
    marginTop: 16,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: '#2a2a2a',
  },
  unrankedTitle: {
    fontFamily: Fonts.display,
    fontSize: 18,
    letterSpacing: 2,
    color: '#fff',
    marginTop: 4,
  },
  unrankedSub: {
    fontFamily: Fonts.body,
    fontSize: 13,
    color: '#555',
    textAlign: 'center',
    lineHeight: 20,
  },
  errorCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(230,48,48,0.06)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(230,48,48,0.2)',
    paddingVertical: 28,
    paddingHorizontal: 20,
    gap: 8,
    marginTop: 16,
  },
  errorText: {
    fontFamily: Fonts.body,
    fontSize: 13,
    color: '#b0b0b0',
  },
  retryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 4,
    backgroundColor: Colors.accent,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 10,
  },
  retryText: {
    fontFamily: Fonts.display,
    fontSize: 12,
    letterSpacing: 2,
    color: '#fff',
  },
  loadMoreBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    marginVertical: 4,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#2a2a2a',
    backgroundColor: '#1e1e1e',
    minHeight: 46,
  },
  loadMoreText: {
    fontFamily: Fonts.display,
    fontSize: 12,
    letterSpacing: 3,
    color: '#fff',
  },
  refreshBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    marginTop: 4,
  },
  refreshText: {
    fontFamily: Fonts.display,
    fontSize: 10,
    letterSpacing: 2,
    color: '#383838',
  },
});
